<Project>
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>GraphSystem</RootNamespace>
    <AssemblyName>GraphD3D</AssemblyName>
    <MyType>Windows</MyType>
    <TargetFramework>net48</TargetFramework>
    <OptionInfer>On</OptionInfer>
    <OutputPath>..\..\Bin\</OutputPath>
    <BaseIntermediateOutputPath>..\..\Obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <DocumentationFile>GraphD3D.xml</DocumentationFile>
    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
    <WarningsAsErrors></WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <DefineDebug>false</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <Optimize>true</Optimize>
    <DocumentationFile>GraphD3D.xml</DocumentationFile>
    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
    <WarningsAsErrors></WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SlimDX">
      <HintPath>..\Lib\SlimDX\net40\x64\SlimDX.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GraphSystem\GraphSystem.vbproj" />
  </ItemGroup>
</Project>
