<Project>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <StartupObject>Scaler.My.MyApplication</StartupObject>
    <RootNamespace>Scaler</RootNamespace>
    <AssemblyName>Scaler</AssemblyName>
    <MyType>WindowsForms</MyType>
    <TargetFramework>net48</TargetFramework>
    <ApplicationIcon>CommDevToolkit.ico</ApplicationIcon>
    <OptionInfer>On</OptionInfer>
    <OutputPath>..\..\Bin\</OutputPath>
    <BaseIntermediateOutputPath>..\..\Obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <DocumentationFile>Scaler.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <DefineDebug>false</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <Optimize>true</Optimize>
    <DocumentationFile>Scaler.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Update="Scaler.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Scaler.Designer.vb">
      <DependentUpon>Scaler.vb</DependentUpon>
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Scaler.resx">
      <SubType>Designer</SubType>
      <DependentUpon>Scaler.vb</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
</Project>
