<Project>
  <PropertyGroup>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
  </ItemGroup>
</Project>
