name: Build Projects

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Build Script
      shell: cmd
      run: |
        set SUB_NO_PAUSE_SYMBOL=1
        pushd Src
        call Build.cmd || exit /b 1
        call Clear.cmd
        popd
      env:
        NO_PAUSE_SYMBOL: 1

    - name: Upload Binaries
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Tools
        path: Bin/
